# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 094052340c801a5ec1fbcf6dc7478eb14b9efdd3d353e6f70227f875ed39a97f43090928d579703ed5cf0449df5a130452aa62976d12cbd4b641035d8bab5a92

test:
  secret_key_base: 782962442a903b36b2c5d378e420ba69547683746e09aee374e4b6b6b83a3707abc824f3460f6d8e485f6465ca8d222b40b6cd6e2c969622ddbb6ae8263b0a25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
